In [2]:
import numpy as np
import random

def kMedoids(D, k, tmax=100):
    # determine dimensions of distance matrix D
    m, n = D.shape

    if k > n:
        raise Exception('too many medoids')

    # find a set of valid initial cluster medoid indices since we
    # can't seed different clusters with two points at the same location
    valid_medoid_inds = set(range(n))
    invalid_medoid_inds = set([])
    rs,cs = np.where(D==0)
    # the rows, cols must be shuffled because we will keep the first duplicate below
    index_shuf = list(range(len(rs)))
    np.random.shuffle(index_shuf)
    rs = rs[index_shuf]
    cs = cs[index_shuf]
    for r,c in zip(rs,cs):
        # if there are two points with a distance of 0...
        # keep the first one for cluster init
        if r < c and r not in invalid_medoid_inds:
            invalid_medoid_inds.add(c)
    valid_medoid_inds = list(valid_medoid_inds - invalid_medoid_inds)

    if k > len(valid_medoid_inds):
        raise Exception('too many medoids (after removing {} duplicate points)'.format(
            len(invalid_medoid_inds)))

    # randomly initialize an array of k medoid indices
    M = np.array(valid_medoid_inds)
    np.random.shuffle(M)
    M = np.sort(M[:k])

    # create a copy of the array of medoid indices
    Mnew = np.copy(M)

    # initialize a dictionary to represent clusters
    C = {}
    for t in range(tmax):
        # determine clusters, i. e. arrays of data indices
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]
        # update cluster medoids
        for kappa in range(k):
            J = np.mean(D[np.ix_(C[kappa],C[kappa])],axis=1)
            j = np.argmin(J)
            Mnew[kappa] = C[kappa][j]
        np.sort(Mnew)
        # check for convergence
        if np.array_equal(M, Mnew):
            break
        M = np.copy(Mnew)
    else:
        # final update of cluster memberships
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]

# return results
    return M, C

from sklearn.metrics.pairwise import pairwise_distances
import numpy as np
import pandas as pd

# 3 points in dataset
iris_data = pd.read_csv('/home/karthik/anaconda_python/411631_kelab_record/411631_python_using/clustering/kmedoids/Iris.csv' , 
    sep= ',')
data = iris_data.values[:, 1:4]

# distance matrix
D = pairwise_distances(data, metric='euclidean')

# split into 2 clusters
M, C = kMedoids(D, 3)

print('medoids:')
for point_idx in M:
    print( data[point_idx] )

print('')
print('clustering result:')
for label in C:
    for point_idx in C[label]:
        print('label {0}:　{1}'.format(label, data[point_idx]))

medoids:
[5.0 3.4 1.5]
[6.7 3.1 5.6]
[6.0 2.9 4.5]

clustering result:
label 0:　[5.1 3.5 1.4]
label 0:　[4.9 3.0 1.4]
label 0:　[4.7 3.2 1.3]
label 0:　[4.6 3.1 1.5]
label 0:　[5.0 3.6 1.4]
label 0:　[5.4 3.9 1.7]
label 0:　[4.6 3.4 1.4]
label 0:　[5.0 3.4 1.5]
label 0:　[4.4 2.9 1.4]
label 0:　[4.9 3.1 1.5]
label 0:　[5.4 3.7 1.5]
label 0:　[4.8 3.4 1.6]
label 0:　[4.8 3.0 1.4]
label 0:　[4.3 3.0 1.1]
label 0:　[5.8 4.0 1.2]
label 0:　[5.7 4.4 1.5]
label 0:　[5.4 3.9 1.3]
label 0:　[5.1 3.5 1.4]
label 0:　[5.7 3.8 1.7]
label 0:　[5.1 3.8 1.5]
label 0:　[5.4 3.4 1.7]
label 0:　[5.1 3.7 1.5]
label 0:　[4.6 3.6 1.0]
label 0:　[5.1 3.3 1.7]
label 0:　[4.8 3.4 1.9]
label 0:　[5.0 3.0 1.6]
label 0:　[5.0 3.4 1.6]
label 0:　[5.2 3.5 1.5]
label 0:　[5.2 3.4 1.4]
label 0:　[4.7 3.2 1.6]
label 0:　[4.8 3.1 1.6]
label 0:　[5.4 3.4 1.5]
label 0:　[5.2 4.1 1.5]
label 0:　[5.5 4.2 1.4]
label 0:　[4.9 3.1 1.5]
label 0:　[5.0 3.2 1.2]
label 0:　[5.5 3.5 1.3]
label 0:　[4.9 3.1 1.5]
label 0:　[4.4 3.0 1.3]
label 0:　[5.1 3.4 1.5]
label 0:　